
from turtle import clear, pencolor, penup
a = 100
b = -300
c = a + 20

import turtle
nhan = turtle.Screen()            
nhan = turtle.Turtle()  

nhan.penup ()
nhan.goto(b,0)  
nhan.pendown ()


nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.back(a)
nhan.color('red')
nhan.left(135)
nhan.forward(70)
nhan.right(90)
nhan.forward(70)
nhan.right(45)
nhan.left(90)
nhan.color('black')

nhan.penup ()
nhan.goto(b+c,0)  
nhan.pendown ()

nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.back(a)
nhan.color('red')
nhan.left(135)
nhan.forward(70)
nhan.right(90)
nhan.forward(70)
nhan.right(45)
nhan.left(90)
nhan.color('black')

nhan.penup ()
nhan.goto(b+2*c,0)  
nhan.pendown ()

nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.back(a)
nhan.color('red')
nhan.left(135)
nhan.forward(70)
nhan.right(90)
nhan.forward(70)
nhan.right(45)
nhan.left(90)
nhan.color('black')

nhan.penup ()
nhan.goto(b+3*c,0)  
nhan.pendown ()

nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.back(a)
nhan.color('red')
nhan.left(135)
nhan.forward(70)
nhan.right(90)
nhan.forward(70)
nhan.right(45)
nhan.left(90)
nhan.color('black')

nhan.penup ()
nhan.goto(b+4*c,0)  
nhan.pendown ()

nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.left(90)
nhan.forward(a)
nhan.back(a)
nhan.color('red')
nhan.left(135)
nhan.forward(70)
nhan.right(90)
nhan.forward(70)
nhan.right(45)
nhan.left(90)
nhan.color('black')

turtle.done